#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-Angular-Bootstrap
Version  : 0.11.0.8
Release  : 15
URL      : http://pypi.debian.net/XStatic-Angular-Bootstrap/XStatic-Angular-Bootstrap-0.11.0.8.tar.gz
Source0  : http://pypi.debian.net/XStatic-Angular-Bootstrap/XStatic-Angular-Bootstrap-0.11.0.8.tar.gz
Summary  : XStatic-Angular-Bootstrap
Group    : Development/Tools
License  : MIT
Requires: XStatic-Angular-Bootstrap-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : setuptools_scm
BuildRequires : setuptools_scm-python
BuildRequires : tox
BuildRequires : virtualenv
BuildRequires : wheel-python

%description
XStatic-Angular-Bootstrap
-------------------------
Angular-Bootstrap JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-Angular-Bootstrap package.
Group: Default
Provides: xstatic-angular-bootstrap-python

%description python
python components for the XStatic-Angular-Bootstrap package.


%prep
%setup -q -n XStatic-Angular-Bootstrap-0.11.0.8

%build
export LANG=C
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
